config/routes.rb
Rails.application.routes.draw do
  resources :products
  root 'pages#home'

  get 'posts', to: 'posts#index', as: 'posts'
  
  get '/about_us', to: 'pages#about_us'
  get 'greet/:name', to: 'pages#greet', as: 'greet'


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    #one to many
    belongs_to :user
    has_and_belongs_to_many :courses
    has_many :comments, as: :commentable
    #scopes para filtrar
    scope :published, -> { where(published: true)}
    scope :created_before, -> (time) { where("created_at < ?", time)}
    #validadores
    validates :title, presence: true
    #callbacks
    before_create :fill_body
    
    def fill_body
        self.body = 'lorem ipsum'
    end

end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_many :post
    has_and_belongs_to_many :courses
    has_many :comments, as: :commentable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    
  end

  def about_us
    @about = "Lorem Ipsum"
  end

  def greet
    @greeting = "David R Zuluaga"
    @hello = params[:name]
    @post = Post.all
  end

  def contact
    @contacts = [David, 3019002134]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
    end

    def show
        @product = Product.find(params[:id])
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new(product_params)
        if @product.save
            redirect_to products_path
        else
            render :new
        end
    end

    def edit
        @product = Product.find(params[:id])
    end
    def destroy
        product = Product.find(params[:id])
        product.destroy
        flash[ :notice] = "El producto ha sido eliminado exitosamente"
        redirect_to products_path
    end
    
    private

    def product_params
        params.require(:product).permit(:name, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <li><%= link_to 'Hello', greet_url('about_us') %> </li>
    </ul>
    <% flash.each do |name, msg|%>
    <%=content_tag :div, msg, class: name%>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/pages/about_us.html.erb
<p>Pages for Creation <%=@about%></p>

app/views/pages/contact.erb
<h1>Buenos Dias</h1>

app/views/pages/freaking.html.erb
<h1>Buenos Dias</h1>

app/views/pages/greet.html.erb
<p>Hola <%=@hello%> <%=@greeting%></p>

<ul> 
<%@post.each do |post|%>
<li><%= post.title %> - <%= post.body %> </li>
<% end %>
</ul>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<a></a>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/products/_form.html.erb
<h1><%=action%> Product</h1>

<%= form_for @product do |f| %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
   <div>
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%= render 'form', product: @product, action: 'edit'%>

app/views/products/index.html.erb
<h1>Productos</h1>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Precio</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td>
          <%= link_to "Mostrar", product %>
          <%= link_to "Editar", edit_product_path(product) %>
          <%= link_to "Eliminar", product, method: :delete, data: { confirm: "¿Estás seguro de eliminar este producto?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'create', new_product_path %>

app/views/products/new.html.erb
<%= render 'form', product: @product, action: 'new'%>